# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache


minimal_mistakes_skin    : "default" 
title                    : "Akshay Sharma"
name                     : "Akshay Sharma"
description              : >- # this means to ignore newlines until "baseurl:"
  Welcome to Akshay Sharma's personal blog. Here you will find my
  publications, resume, posts/blogs. You can review my open source 
  contributions, follow my twitter handle, and get my book reading updates. 
url                      : "https://akshay326.com"
baseurl                  : ""
teaser                   : "/assets/images/dp.jpg"
search                   : true
search_full_content      : true # true, false (default)
search_provider          : "lunr"
lunr:
  search_within_pages    : true
repository               : akshay326/akshay326.github.io


# Site Author
author:
  name             : "Akshay Sharma"
  avatar           : "/assets/images/dp.jpg"
  bio              : "NLP @ Klarity.ai -- CS @ Columbia"
  location         : "San Francisco"
  links:
    - label: "Book A Call"
      icon: "fas fa-fw fa-link"
      url: "https://topmate.io/akshay_326"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/akshay326_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/akshay326"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/akshay326"


# Site Footer
footer:
  links:
    - label: "Book A Call"
      icon: "fas fa-fw fa-link"
      url: "https://topmate.io/akshay_326"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/akshay326_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/akshay326"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/akshay326"


# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true